default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: apireact-activeadmin_development


test:
  <<: *default
  database: apireact-activeadmin_test